### ISSUE TITLE
资源推荐，免费的超级外链工具

### ISSUE THREAD

**Issue by cmhaoso** [afterwork-design/castalia#27]
https://maxed.top/seo/

**Comment by Fish-four** [comment]
分类：图片
名称：POND5
URL：https://www.pond5.com/public-domain
描述：公共领域，有图片，音乐，模型等数千个历史媒体文件
图片：
![QQ截图20220328093925](https://user-images.githubusercontent.com/102455939/160312318-6b565601-4c04-4591-adc7-95beaf1aebdd.png)

**Comment by tangweijuan** [comment]
@cmhaoso 这个网站不太适合公开宣传，此次不添加

**Comment by tangweijuan** [comment]
@Fish-four POND5资源不错，已添加到网站
