### ISSUE TITLE
打包项目 npm build 报错

### ISSUE THREAD

**Issue by tao-xiaoxin** [afterwork-design/castalia#41]
报错：error - ESLint must be installed in order to run during builds: yarn add --dev eslint
请问大佬有何解决办法吗？
node 版本就是readme中指定的版本

**Comment by gyf9835** [comment]
我发现报错不会影响打包，只要把`next.config.js`中的
```
assetPrefix: IsDevelopment ? "" : "/castalia",
```
改为
```
assetPrefix: "",
```
然后执行`npm run build`打包，`npm run export`导出
就可以把项目打包到`out`文件夹下了

**Comment by tao-xiaoxin** [comment]
感谢大佬成功，完美

**Comment by pengfeiw** [comment]
这个主要是为了处理发布的资源路径的，如果你的资源路径就在服务器根目录下，那么就可以直接用 `""`, 这个项目的资源路径是 `/castailia`, 所以生产环境的 `assetPrefix` 为 `/castalia`
