### ISSUE TITLE
可以添加深色模式（Dark Mode ）吗？

### ISSUE THREAD

**Issue by forecho** [afterwork-design/castalia#49]
网站设计的很漂亮，要是能添加 Dark Mode 就更好了

**Comment by pengfeiw** [comment]
没有放开深色模式，最初没有考虑深色模式。但是这个项目采用的是 [chakra ui](https://chakra-ui.com/)，它是支持深色模式的，需要自己改一下代码，切换到深色模式，教程在这里 [color mode](https://chakra-ui.com/docs/styled-system/color-mode)

**Comment by pengfeiw** [comment]
你可以点击 [chakra ui](https://chakra-ui.com/) 网页右上角的按钮切换到深色模式，查看组件深色模式效果。
![image](https://user-images.githubusercontent.com/37898750/210532255-5b83c9a5-f66d-4fa2-8789-0f68c7604580.png)
